<a href="https://colab.research.google.com/github/gourim2523-arch/DATA-ACQUISITION-CASE-STUDY/blob/main/Data_Acquisition_Casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd

Task 1: Read the Population dataset from the CSV file.

In [70]:

population=pd.read_csv("/content/population.csv")
population.head(5)

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [71]:
population.shape

(25, 2)

In [72]:
population.dtypes

country       object
population     int64
dtype: object

Task 2: Read the GDP dataset from the Excel file.

In [73]:
gdp=pd.read_excel("/content/gdp.xlsx")
gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [74]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

Task 3: Read the Internet Users dataset from the JSON file.

In [75]:
internet_users=pd.read_json("/content/internet_users.json")
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [76]:
user=pd.DataFrame(internet_users)
user

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

Task 4: Read the Literacy Rate dataset from the XML file.

In [77]:
literacy_rate=pd.read_xml("/content/literacy_rate.xml")
literacy_rate

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [78]:
literacy=pd.DataFrame(literacy_rate)
literacy.head()

            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0

Task 5: Explore each dataset and find:
- Number of rows
- Number of columns
- Column names
- Data types
- Missing values
- Duplicate records

In [79]:
population.shape

(25, 2)

In [80]:
gdp.shape

(25, 2)

In [81]:
literacy.shape

(25, 2)

In [82]:
user.shape

(25, 2)

In [83]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     25 non-null     object
 1   population  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [84]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [85]:
user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         25 non-null     object
 1   internet_users  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [86]:
literacy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           25 non-null     object
 1   literacy_rate  25 non-null     float64
dtypes: float64(1), object(1)
memory usage: 532.0+ bytes

In [87]:
population.isnull().sum()

country       0
population    0
dtype: int64

In [88]:
gdp.isnull().sum()

Country    0
GDP        0
dtype: int64

In [89]:
user.isnull().sum()

country           0
internet_users    0
dtype: int64

In [90]:
literacy.isnull().sum()

name             0
literacy_rate    0
dtype: int64

In [91]:
population.duplicated().sum()

np.int64(0)

In [92]:
gdp.duplicated().sum()

np.int64(0)

In [93]:
user.duplicated().sum()

np.int64(0)

In [94]:
literacy.duplicated().sum()

np.int64(0)

Task 6: Rename columns wherever necessary so that all datasets have a common column name for merging.

In [95]:
gdp.rename(columns={"Country":"country"},inplace=True)
gdp

           country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

Task 6: Rename columns wherever necessary so that all datasets have a common column name for merging.

In [96]:
literacy.rename(columns={"name":"country"},inplace=True)
literacy

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

Task 8: Merge all four datasets into one DataFrame.

In [97]:
mergedd=pd.merge(population,gdp,on="country",how="inner")

In [98]:
mergedd=pd.merge(mergedd,user,on="country",how="inner")

In [99]:
mergedd=pd.merge(mergedd,literacy,on="country",how="inner")
mergedd

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

Task 9: Create the following calculated columns:
1. Internet Penetration (%)
2. GDP Per Capita

In [105]:
mergedd["Internet_Penetration"]=(mergedd["internet_users"]/mergedd["population"]*100).round(2)
mergedd

,country,population,GDP,internet_users,literacy_rate,Internet_Penetration,GDP_Per_Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.092144
1,China,1411778724,19230000,1080000000,97.2,76.50,0.013621
2,India,1380004385,4187000,850000000,77.7,61.59,0.003034
3,Japan,125836021,4180000,118000000,99.0,93.77,0.033218
4,Germany,83240525,4744000,79000000,99.0,94.91,0.056991
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.056551
6,France,65273511,3211000,62000000,99.0,94.98,0.049193
7,Italy,60461826,2420000,56000000,99.0,92.62,0.040025
8,Canada,38005238,2250000,36000000,99.0,94.72,0.059202
9,Australia,25687041,1880000,24000000,99.0,93.43,0.073189
10,Brazil,212559417,2330000,181000000,93.2,85.15,0.010962
11,Russia,145934462,2200000,125000000,99.7,85.65,0.015075
12,South Korea,51780579,1800000,50000000,98.8,96.56,0.034762
13,Spain,46754778,1710000,44000000,98.6,94.11,0.036574
14,Mexico,128932753,1810000,102000000,95.4,79.11,0.014038
15,Indonesia,273523615,1500000,212000000,96.0,77.51,0.005484
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.031597
17,Turkey,84339067,1350000,69000000,96.7,81.81,0.016007
18,South Africa,59308690,410000,43000000,95.0,72.50,0.006913
19,Argentina,45195774,640000,41000000,99.1,90.72,0.014161
20,Netherlands,17441139,1150000,17000000,99.0,97.47,0.065936
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.108612
22,Sweden,10353442,650000,10100000,99.0,97.55,0.062781
23,Norway,5421241,580000,5300000,100.0,97.76,0.106987
24,Singapore,5850342,530000,5600000,97.5,95.72,0.090593

In [106]:
mergedd["GDP_Per_Capita"]=(mergedd["GDP"]/mergedd["population"]).round(2)
mergedd

,country,population,GDP,internet_users,literacy_rate,Internet_Penetration,GDP_Per_Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
6,France,65273511,3211000,62000000,99.0,94.98,0.05
7,Italy,60461826,2420000,56000000,99.0,92.62,0.04
8,Canada,38005238,2250000,36000000,99.0,94.72,0.06
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07
10,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
11,Russia,145934462,2200000,125000000,99.7,85.65,0.02
12,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
13,Spain,46754778,1710000,44000000,98.6,94.11,0.04
14,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
15,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
17,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
18,South Africa,59308690,410000,43000000,95.0,72.50,0.01
19,Argentina,45195774,640000,41000000,99.1,90.72,0.01
20,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
22,Sweden,10353442,650000,10100000,99.0,97.55,0.06
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09

Task 10: Create a SQLite database and store the final merged dataset into a table named 'country_statistics'.

In [107]:
import sqlite3
import pandas as pd

In [108]:
conn = sqlite3.connect("country_statistics.db")

In [109]:
mergedd.to_sql(
    "country_statistics",
    conn,
    if_exists="replace",
    index=False
)

25

Task 11: Verify that the data has been loaded successfully by retrieving the first five records from the SQLite table.

In [111]:
query="SELECT * FROM country_statistics LIMIT 5"
cursor=conn.cursor()
cursor.execute(query)
result=cursor.fetchall()
result

[('United States', 331002651, 30500000, 312000000, 99.0, 94.26, 0.09),
 ('China', 1411778724, 19230000, 1080000000, 97.2, 76.5, 0.01),
 ('India', 1380004385, 4187000, 850000000, 77.7, 61.59, 0.0),
 ('Japan', 125836021, 4180000, 118000000, 99.0, 93.77, 0.03),
 ('Germany', 83240525, 4744000, 79000000, 99.0, 94.91, 0.06)]

1. List the Top 5 countries by GDP.

In [115]:
top5_gdp = mergedd.sort_values(by="GDP", ascending=False).head(5)

(top5_gdp[["country", "GDP"]])

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

2. List the Top 5 countries by population.

In [117]:
top5_population = mergedd.sort_values(
    by="population",
    ascending=False
).head(5)

(top5_population[["country", "population"]])

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

3. Calculate the average literacy rate.

In [119]:
average_literacy = mergedd["literacy_rate"].mean()
average_literacy

np.float64(97.248)

4. List all countries having a literacy rate greater than 90%.

In [120]:
high_literacy = mergedd[ mergedd["literacy_rate"] > 90][["country", "literacy_rate"]]
high_literacy

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

5. List all countries having an internet penetration greater than 70%.

In [123]:
high_internet = mergedd[mergedd["Internet_Penetration"] > 70][["country", "Internet_Penetration"]]
high_internet

           country  Internet_Penetration
0    United States                 94.26
1            China                 76.50
3            Japan                 93.77
4          Germany                 94.91
5   United Kingdom                 97.22
6           France                 94.98
7            Italy                 92.62
8           Canada                 94.72
9        Australia                 93.43
10          Brazil                 85.15
11          Russia                 85.65
12     South Korea                 96.56
13           Spain                 94.11
14          Mexico                 79.11
15       Indonesia                 77.51
16    Saudi Arabia                 97.66
17          Turkey                 81.81
18    South Africa                 72.50
19       Argentina                 90.72
20     Netherlands                 97.47
21     Switzerland                 98.21
22          Sweden                 97.55
23          Norway                 97.76
24       Singapore                 95.72

6. List the Top 5 countries by GDP per capita.

In [130]:
top5_gdp_capita = mergedd.sort_values(by="GDP_Per_Capita",ascending=False).head(5)[["country", "GDP_Per_Capita"]]
top5_gdp_capita

          country  GDP_Per_Capita
21    Switzerland            0.11
23         Norway            0.11
24      Singapore            0.09
0   United States            0.09
9       Australia            0.07

7. Calculate the total population represented in the dataset.

In [131]:
total_population = mergedd["population"].sum()
total_population

np.int64(4720039725)

8. Calculate the average internet penetration across all countries.

In [132]:
average_internet_penetration = mergedd["Internet_Penetration"].mean()
average_internet_penetration

np.float64(89.6596)

9. Identify the country having the highest number of internet users.

In [133]:
highest_internet_users = mergedd.loc[mergedd["internet_users"].idxmax(),["country", "internet_users"]]
highest_internet_users

country                China
internet_users    1080000000
Name: 1, dtype: object

10. Find the correlation between Literacy Rate and Internet Penetration.

In [135]:
correlation = mergedd["literacy_rate"].corr( mergedd["Internet_Penetration"])
correlation

np.float64(0.77279756813985)

11. Display the Top 5 countries by GDP using SQLite queries.

In [136]:
query1 = """
SELECT country, gdp
FROM country_statistics
ORDER BY gdp DESC
LIMIT 5
"""

cursor = conn.cursor()
cursor.execute(query1)
result = cursor.fetchall()
result

[('United States', 30500000),
 ('China', 19230000),
 ('Germany', 4744000),
 ('India', 4187000),
 ('Japan', 4180000)]

12. Find the average literacy rate using SQLite queries.

In [138]:
query2= """
SELECT AVG(literacy_rate)
FROM country_statistics
"""

cursor = conn.cursor()
cursor.execute(query2)
result = cursor.fetchall()
result

[(97.24799999999999,)]

13. Display all countries having literacy rate above 90% using SQLite queries.

In [139]:
query3 = """
SELECT country, literacy_rate
FROM country_statistics
WHERE literacy_rate > 90
"""

cursor = conn.cursor()
cursor.execute(query3)
result = cursor.fetchall()
result

[('United States', 99.0),
 ('China', 97.2),
 ('Japan', 99.0),
 ('Germany', 99.0),
 ('United Kingdom', 99.0),
 ('France', 99.0),
 ('Italy', 99.0),
 ('Canada', 99.0),
 ('Australia', 99.0),
 ('Brazil', 93.2),
 ('Russia', 99.7),
 ('South Korea', 98.8),
 ('Spain', 98.6),
 ('Mexico', 95.4),
 ('Indonesia', 96.0),
 ('Saudi Arabia', 97.3),
 ('Turkey', 96.7),
 ('South Africa', 95.0),
 ('Argentina', 99.1),
 ('Netherlands', 99.0),
 ('Switzerland', 99.0),
 ('Sweden', 99.0),
 ('Norway', 100.0),
 ('Singapore', 97.5)]

14. Find the Top 5 countries with the highest internet penetration using SQLite queries.

In [140]:
query4 = """
SELECT country, internet_penetration
FROM country_statistics
ORDER BY internet_penetration DESC
LIMIT 5
"""

cursor = conn.cursor()
cursor.execute(query4)
result = cursor.fetchall()
result

[('Switzerland', 98.21),
 ('Norway', 97.76),
 ('Saudi Arabia', 97.66),
 ('Sweden', 97.55),
 ('Netherlands', 97.47)]

15. Calculate the total population using SQLite queries.

In [141]:
query5 = """
SELECT SUM(population)
FROM country_statistics
"""

cursor = conn.cursor()
cursor.execute(query5)
result = cursor.fetchall()
result

[(4720039725,)]

16. Find the country with the highest GDP per capita using SQLite queries.

In [142]:
query6 = """
SELECT country, gdp_per_capita
FROM country_statistics
ORDER BY gdp_per_capita DESC
LIMIT 1
"""

cursor = conn.cursor()
cursor.execute(query6)
result = cursor.fetchall()
result

[('Switzerland', 0.11)]

17. Export the final merged dataset as a CSV file.

In [143]:
mergedd.to_csv("final_country_statistics.csv", index=False)

18. Sort the dataset in descending order of GDP Per Capita and display the Top 10 countries.

In [144]:
query7 = """
SELECT country, gdp_per_capita
FROM country_statistics
ORDER BY gdp_per_capita DESC
LIMIT 10
"""

cursor = conn.cursor()
cursor.execute(query7)
result = cursor.fetchall()
result

[('Switzerland', 0.11),
 ('Norway', 0.11),
 ('United States', 0.09),
 ('Singapore', 0.09),
 ('Australia', 0.07),
 ('Netherlands', 0.07),
 ('Germany', 0.06),
 ('United Kingdom', 0.06),
 ('Canada', 0.06),
 ('Sweden', 0.06)]

Write a short summary (5–6 points) explaining your ETL process, including:
● Data sources used
● Data cleaning steps
● Transformations performed
● Database loading process
● Key insights obtained from the analysis

1. Data Sources Used
Collected data from multiple file formats:
gdp.xlsx → GDP data
literacy_rate.xml → Literacy rate data
population.csv → Population data
internet_users.json → Internet usage data
Each dataset contained country-wise statistics.
2. Data Cleaning Steps
Loaded datasets into Pandas DataFrames.
Checked data structure using .info() and verified column names.
Checked for missing/null values using .isnull() and .sum().
Converted columns into appropriate data types (int64, float64, object).
Ensured consistency in the common column country.
3. Transformations Performed
Merged all four datasets using country as the common key.
Used inner join to combine only matching records.
Created derived columns:
Internet Penetration = (internet_users / population) × 100
GDP per Capita = GDP / population
Sorted and analyzed the transformed dataset.
4. Database Loading Process
Created a SQLite database using the sqlite3 library.
Loaded the final merged DataFrame into the table country_statistics using Pandas to_sql().
Stored the processed dataset for SQL-based querying and analysis.
5. Data Analysis Performed
Identified the Top 5 countries by GDP.
Calculated average literacy rate and total population.
Found countries with literacy rate above 90%.
Determined Top countries by internet penetration and highest GDP per capita.
6. Key Insights Obtained
Countries with higher literacy rates generally showed higher internet penetration.
GDP per capita helped compare economic performance more accurately than total GDP.
Data integration from multiple sources enabled more meaningful country-level analysis.